language: php
php:
  - '7.0'
  - '7.1'

before_script:
  - travis_retry composer self-update
  - composer install --prefer-source --no-interaction

script:
- vendor/bin/phpunit --verbose --coverage-text --coverage-clover=coverage.xml tests/
